# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nagomi/v1/enums.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 6, 32, 1, "", "nagomi/v1/enums.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
  b'\n\x15nagomi/v1/enums.proto\x12\tnagomi.v1*\xa9\x01\n\x0b\x41\x63\x63ountType\x12\x17\n\x13\x41\x43\x43OUNT_UNSPECIFIED\x10\x00\x12\x14\n\x10\x41\x43\x43OUNT_CHEQUING\x10\x01\x12\x13\n\x0f\x41\x43\x43OUNT_SAVINGS\x10\x02\x12\x17\n\x13\x41\x43\x43OUNT_CREDIT_CARD\x10\x03\x12\x16\n\x12\x41\x43\x43OUNT_INVESTMENT\x10\x04\x12\x11\n\rACCOUNT_OTHER\x10\x05\x12\x12\n\x0e\x41\x43\x43OUNT_FRIEND\x10\x06*a\n\x14TransactionDirection\x12\x19\n\x15\x44IRECTION_UNSPECIFIED\x10\x00\x12\x16\n\x12\x44IRECTION_INCOMING\x10\x01\x12\x16\n\x12\x44IRECTION_OUTGOING\x10\x02*\xd6\x01\n\x11TransactionSource\x12"\n\x1eTRANSACTION_SOURCE_UNSPECIFIED\x10\x00\x12\x1d\n\x19TRANSACTION_SOURCE_MANUAL\x10\x01\x12\x1c\n\x18TRANSACTION_SOURCE_EMAIL\x10\x02\x12 \n\x1cTRANSACTION_SOURCE_CONNECTOR\x10\x03\x12 \n\x1cTRANSACTION_SOURCE_STATEMENT\x10\x04\x12\x1c\n\x18TRANSACTION_SOURCE_SPLIT\x10\x05*\xf1\x01\n\nPeriodType\x12\x1b\n\x17PERIOD_TYPE_UNSPECIFIED\x10\x00\x12\x16\n\x12PERIOD_TYPE_7_DAYS\x10\x01\x12\x17\n\x13PERIOD_TYPE_30_DAYS\x10\x02\x12\x17\n\x13PERIOD_TYPE_90_DAYS\x10\x03\x12\x16\n\x12PERIOD_TYPE_CUSTOM\x10\x04\x12\x18\n\x14PERIOD_TYPE_3_MONTHS\x10\x05\x12\x18\n\x14PERIOD_TYPE_6_MONTHS\x10\x06\x12\x16\n\x12PERIOD_TYPE_1_YEAR\x10\x07\x12\x18\n\x14PERIOD_TYPE_ALL_TIME\x10\x08*l\n\x0bGranularity\x12\x1b\n\x17GRANULARITY_UNSPECIFIED\x10\x00\x12\x13\n\x0fGRANULARITY_DAY\x10\x01\x12\x14\n\x10GRANULARITY_WEEK\x10\x02\x12\x15\n\x11GRANULARITY_MONTH\x10\x03\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "nagomi.v1.enums_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals["_ACCOUNTTYPE"]._serialized_start = 37
  _globals["_ACCOUNTTYPE"]._serialized_end = 206
  _globals["_TRANSACTIONDIRECTION"]._serialized_start = 208
  _globals["_TRANSACTIONDIRECTION"]._serialized_end = 305
  _globals["_TRANSACTIONSOURCE"]._serialized_start = 308
  _globals["_TRANSACTIONSOURCE"]._serialized_end = 522
  _globals["_PERIODTYPE"]._serialized_start = 525
  _globals["_PERIODTYPE"]._serialized_end = 766
  _globals["_GRANULARITY"]._serialized_start = 768
  _globals["_GRANULARITY"]._serialized_end = 876
# @@protoc_insertion_point(module_scope)
