# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nagomi/v1/statement_parser.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
  _runtime_version.Domain.PUBLIC, 6, 32, 1, "", "nagomi/v1/statement_parser.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
  b'\n nagomi/v1/statement_parser.proto\x12\tnagomi.v1\x1a\x16google/type/date.proto\x1a\x15nagomi/v1/enums.proto"2\n\x15ParseStatementRequest\x12\x19\n\x08pdf_data\x18\x01 \x01(\x0cR\x07pdfData"R\n\x16ParseStatementResponse\x12\x38\n\tstatement\x18\x01 \x01(\x0b\x32\x1a.nagomi.v1.ParsedStatementR\tstatement"\xff\x03\n\x0fParsedStatement\x12\x16\n\x06parser\x18\x01 \x01(\tR\x06parser\x12\x12\n\x04\x62\x61nk\x18\x02 \x01(\tR\x04\x62\x61nk\x12\x39\n\x0c\x61\x63\x63ount_type\x18\x03 \x01(\x0e\x32\x16.nagomi.v1.AccountTypeR\x0b\x61\x63\x63ountType\x12%\n\x0e\x61\x63\x63ount_number\x18\x04 \x01(\tR\raccountNumber\x12\x34\n\x0cperiod_start\x18\x05 \x01(\x0b\x32\x11.google.type.DateR\x0bperiodStart\x12\x30\n\nperiod_end\x18\x06 \x01(\x0b\x32\x11.google.type.DateR\tperiodEnd\x12\x1a\n\x08\x63urrency\x18\x07 \x01(\tR\x08\x63urrency\x12\x37\n\x15opening_balance_cents\x18\x08 \x01(\x03H\x00R\x13openingBalanceCents\x88\x01\x01\x12\x37\n\x15\x63losing_balance_cents\x18\t \x01(\x03H\x01R\x13\x63losingBalanceCents\x88\x01\x01\x12\x34\n\x05lines\x18\n \x03(\x0b\x32\x1e.nagomi.v1.ParsedStatementLineR\x05linesB\x18\n\x16_opening_balance_centsB\x18\n\x16_closing_balance_cents"\x8c\x02\n\x13ParsedStatementLine\x12%\n\x04\x64\x61te\x18\x01 \x01(\x0b\x32\x11.google.type.DateR\x04\x64\x61te\x12\x39\n\x0cposting_date\x18\x02 \x01(\x0b\x32\x11.google.type.DateH\x00R\x0bpostingDate\x88\x01\x01\x12!\n\x0c\x61mount_cents\x18\x03 \x01(\x03R\x0b\x61mountCents\x12=\n\tdirection\x18\x04 \x01(\x0e\x32\x1f.nagomi.v1.TransactionDirectionR\tdirection\x12 \n\x0b\x64\x65scription\x18\x05 \x01(\tR\x0b\x64\x65scriptionB\x0f\n\r_posting_date2o\n\x16StatementParserService\x12U\n\x0eParseStatement\x12 .nagomi.v1.ParseStatementRequest\x1a!.nagomi.v1.ParseStatementResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "nagomi.v1.statement_parser_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals["_PARSESTATEMENTREQUEST"]._serialized_start = 94
  _globals["_PARSESTATEMENTREQUEST"]._serialized_end = 144
  _globals["_PARSESTATEMENTRESPONSE"]._serialized_start = 146
  _globals["_PARSESTATEMENTRESPONSE"]._serialized_end = 228
  _globals["_PARSEDSTATEMENT"]._serialized_start = 231
  _globals["_PARSEDSTATEMENT"]._serialized_end = 742
  _globals["_PARSEDSTATEMENTLINE"]._serialized_start = 745
  _globals["_PARSEDSTATEMENTLINE"]._serialized_end = 1013
  _globals["_STATEMENTPARSERSERVICE"]._serialized_start = 1015
  _globals["_STATEMENTPARSERSERVICE"]._serialized_end = 1126
# @@protoc_insertion_point(module_scope)
