# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from nagomi.v1 import statement_parser_pb2 as nagomi_dot_v1_dot_statement__parser__pb2


class StatementParserServiceStub(object):
  """internal: nagomi-core -> nagomi-statements. stateless, never writes anywhere.
  an unrecognised document is INVALID_ARGUMENT.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
        channel: A grpc.Channel.
    """
    self.ParseStatement = channel.unary_unary(
      "/nagomi.v1.StatementParserService/ParseStatement",
      request_serializer=nagomi_dot_v1_dot_statement__parser__pb2.ParseStatementRequest.SerializeToString,
      response_deserializer=nagomi_dot_v1_dot_statement__parser__pb2.ParseStatementResponse.FromString,
      _registered_method=True,
    )


class StatementParserServiceServicer(object):
  """internal: nagomi-core -> nagomi-statements. stateless, never writes anywhere.
  an unrecognised document is INVALID_ARGUMENT.
  """

  def ParseStatement(self, request, context):
    """Missing associated documentation comment in .proto file."""
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details("Method not implemented!")
    raise NotImplementedError("Method not implemented!")


def add_StatementParserServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
    "ParseStatement": grpc.unary_unary_rpc_method_handler(
      servicer.ParseStatement,
      request_deserializer=nagomi_dot_v1_dot_statement__parser__pb2.ParseStatementRequest.FromString,
      response_serializer=nagomi_dot_v1_dot_statement__parser__pb2.ParseStatementResponse.SerializeToString,
    ),
  }
  generic_handler = grpc.method_handlers_generic_handler("nagomi.v1.StatementParserService", rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
  server.add_registered_method_handlers("nagomi.v1.StatementParserService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class StatementParserService(object):
  """internal: nagomi-core -> nagomi-statements. stateless, never writes anywhere.
  an unrecognised document is INVALID_ARGUMENT.
  """

  @staticmethod
  def ParseStatement(
    request,
    target,
    options=(),
    channel_credentials=None,
    call_credentials=None,
    insecure=False,
    compression=None,
    wait_for_ready=None,
    timeout=None,
    metadata=None,
  ):
    return grpc.experimental.unary_unary(
      request,
      target,
      "/nagomi.v1.StatementParserService/ParseStatement",
      nagomi_dot_v1_dot_statement__parser__pb2.ParseStatementRequest.SerializeToString,
      nagomi_dot_v1_dot_statement__parser__pb2.ParseStatementResponse.FromString,
      options,
      channel_credentials,
      insecure,
      call_credentials,
      compression,
      wait_for_ready,
      timeout,
      metadata,
      _registered_method=True,
    )
